services:

  backend:
    build: ./backend
    restart: always
    env_file:
      - .env

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

volumes:
  mongo-data: