services:

  client:
    build: ./client
    container_name: react-client
    ports:
      - "5173:5173"
    depends_on:
      - server

  server:
    build: ./server
    container_name: node-server
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: