events {}

http {

  upstream backend_servers {
      server backend1:3000; // Server 1 
      server backend2:3000; // Server 2 
  }

  server {

      listen 80; //nginx default port 

      location /api {
          proxy_pass http://backend_servers; // location of server to pass proxy
      }

  }

}